substitutions:
  _REDACTED_BUCKET_NAME: redacted-forms-bucket
  _IMAGE_TAG: redact-run
  _GCR_HOSTNAME: us.gcr.io
steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - '--no-cache'
    - '-f'
    - /Dockerfile
    - '-t'
    - '$_GCR_HOSTNAME/$PROJECT_ID/$_IMAGE_TAG'
    - '--build-arg'
    - 'ARGPROJECT=$PROJECT_ID ARG_REDACTED_BUCKET_NAME=$_REDACTED_BUCKET_NAME'
    - '.'
  id: Build
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - '$_GCR_HOSTNAME/$PROJECT_ID/$_IMAGE_TAG'
  id: Push